/**
 * A QR encoder — byte mode, error-correction level M, versions 1 to 10.
 *
 * Written rather than installed, for the same reason the PNG encoder and the
 * service worker were: the whole of what this app needs from QR is "turn a
 * short URL into a matrix of booleans", and that is a bounded, fully specified
 * algorithm. A library would ship its own take on modes, levels and versions we
 * will never use.
 *
 * Hand-rolling it is only defensible because it is *verifiable*: the tests
 * decode the output with an independent decoder (`jsqr`, a devDependency) at
 * every payload length across the whole supported range. A QR that encodes to
 * garbage looks exactly like a QR that works, so nothing less would do.
 *
 * Level M corrects roughly 15% damage — the usual choice for a screen, where
 * there is no print smudging but there may be a camera at an angle. Version 10
 * holds 213 bytes at that level, several times the longest URL this app can
 * produce.
 *
 * Reference: ISO/IEC 18004.
 */

/** Total codewords (data + error correction) for versions 1–10. */
const TOTAL_CODEWORDS = [26, 44, 70, 100, 134, 172, 196, 242, 292, 346];

/**
 * Level-M block structure per version: error-correction codewords per block,
 * then the data codeword count of each block. Short blocks come first, as the
 * specification requires for interleaving.
 */
const EC_BLOCKS: readonly { ecPerBlock: number; blocks: readonly number[] }[] = [
  { ecPerBlock: 10, blocks: [16] }, // v1
  { ecPerBlock: 16, blocks: [28] }, // v2
  { ecPerBlock: 26, blocks: [44] }, // v3
  { ecPerBlock: 18, blocks: [32, 32] }, // v4
  { ecPerBlock: 24, blocks: [43, 43] }, // v5
  { ecPerBlock: 16, blocks: [27, 27, 27, 27] }, // v6
  { ecPerBlock: 18, blocks: [31, 31, 31, 31] }, // v7
  { ecPerBlock: 22, blocks: [38, 38, 39, 39] }, // v8
  { ecPerBlock: 22, blocks: [36, 36, 36, 37, 37] }, // v9
  { ecPerBlock: 26, blocks: [43, 43, 43, 43, 44] }, // v10
];

/** Alignment-pattern centre coordinates per version (v1 has none). */
const ALIGNMENT: readonly (readonly number[])[] = [
  [],
  [6, 18],
  [6, 22],
  [6, 26],
  [6, 30],
  [6, 34],
  [6, 22, 38],
  [6, 24, 42],
  [6, 26, 46],
  [6, 28, 50],
];

export const MAX_QR_VERSION = TOTAL_CODEWORDS.length;

// --- GF(256) ---------------------------------------------------------------
// Arithmetic over the field the Reed-Solomon code lives in, generated by
// x^8 + x^4 + x^3 + x^2 + 1 (0x11D).

const EXP = new Uint8Array(512);
const LOG = new Uint8Array(256);

{
  let x = 1;
  for (let i = 0; i < 255; i++) {
    EXP[i] = x;
    LOG[x] = i;
    x <<= 1;
    if (x & 0x100) x ^= 0x11d;
  }
  for (let i = 255; i < 512; i++) EXP[i] = EXP[i - 255]!;
}

// The field tables and polynomial buffers below are indexed strictly within
// their own lengths, by loop bounds derived from those lengths. The `!`
// assertions say exactly that and nothing more — `noUncheckedIndexedAccess`
// cannot see the invariant, and a runtime guard on each access would obscure
// arithmetic that is already dense.
function gfMul(a: number, b: number): number {
  return a === 0 || b === 0 ? 0 : EXP[LOG[a]! + LOG[b]!]!;
}

/** The generator polynomial for `degree` error-correction codewords. */
function generatorPoly(degree: number): Uint8Array {
  let poly = Uint8Array.of(1);
  for (let i = 0; i < degree; i++) {
    const next = new Uint8Array(poly.length + 1);
    for (let j = 0; j < poly.length; j++) {
      next[j]! ^= poly[j]!;
      next[j + 1]! ^= gfMul(poly[j]!, EXP[i]!);
    }
    poly = next;
  }
  return poly;
}

/** Polynomial long division; the remainder is the error-correction block. */
function errorCorrection(data: readonly number[], ecLength: number): Uint8Array {
  const generator = generatorPoly(ecLength);
  const remainder = new Uint8Array(ecLength);

  for (const byte of data) {
    const factor = byte ^ remainder[0]!;
    remainder.copyWithin(0, 1);
    remainder[ecLength - 1] = 0;
    for (let i = 0; i < ecLength; i++) {
      remainder[i]! ^= gfMul(generator[i + 1]!, factor);
    }
  }
  return remainder;
}

// --- Bit stream ------------------------------------------------------------

class BitBuffer {
  private readonly bits: number[] = [];

  push(value: number, length: number): void {
    for (let i = length - 1; i >= 0; i--) this.bits.push((value >>> i) & 1);
  }

  get length(): number {
    return this.bits.length;
  }

  /** Pads to a byte boundary and returns codewords. */
  toCodewords(): number[] {
    while (this.bits.length % 8 !== 0) this.bits.push(0);

    const bytes: number[] = [];
    for (let i = 0; i < this.bits.length; i += 8) {
      let byte = 0;
      for (let j = 0; j < 8; j++) byte = (byte << 1) | (this.bits[i + j] ?? 0);
      bytes.push(byte);
    }
    return bytes;
  }
}

/** The block structure for a version, which the caller has already validated. */
function structureOf(version: number): { ecPerBlock: number; blocks: readonly number[] } {
  const structure = EC_BLOCKS[version - 1];
  if (!structure) throw new RangeError(`No QR structure for version ${version}`);
  return structure;
}

function dataCapacity(version: number): number {
  const { ecPerBlock, blocks } = structureOf(version);
  return (TOTAL_CODEWORDS[version - 1] ?? 0) - ecPerBlock * blocks.length;
}

/** The smallest version that fits `byteLength`, or null if nothing does. */
function chooseVersion(byteLength: number): number | null {
  for (let version = 1; version <= MAX_QR_VERSION; version++) {
    // 4 mode bits + the character-count field + the data itself.
    const countBits = version < 10 ? 8 : 16;
    const needed = 4 + countBits + byteLength * 8;
    if (needed <= dataCapacity(version) * 8) return version;
  }
  return null;
}

function encodeData(bytes: Uint8Array, version: number): number[] {
  const capacity = dataCapacity(version);
  const buffer = new BitBuffer();

  buffer.push(0b0100, 4); // byte mode
  buffer.push(bytes.length, version < 10 ? 8 : 16);
  for (const byte of bytes) buffer.push(byte, 8);

  // Terminator: up to four zero bits, truncated if the capacity is tight.
  buffer.push(0, Math.min(4, capacity * 8 - buffer.length));

  const codewords = buffer.toCodewords();
  // Alternating pad bytes, as specified.
  for (let i = 0; codewords.length < capacity; i++) {
    codewords.push(i % 2 === 0 ? 0xec : 0x11);
  }
  return codewords;
}

/**
 * Splits into blocks, computes error correction, and interleaves.
 *
 * Interleaving is what makes the code robust to a *contiguous* smudge: damage
 * concentrated in one region of the symbol is spread across every block rather
 * than destroying one of them outright.
 */
function interleave(codewords: readonly number[], version: number): number[] {
  const { ecPerBlock, blocks } = structureOf(version);

  const dataBlocks: number[][] = [];
  const ecBlocks: Uint8Array[] = [];
  let offset = 0;

  for (const size of blocks) {
    const block = codewords.slice(offset, offset + size);
    offset += size;
    dataBlocks.push(block);
    ecBlocks.push(errorCorrection(block, ecPerBlock));
  }

  const result: number[] = [];
  const longest = Math.max(...blocks);
  for (let i = 0; i < longest; i++) {
    for (const block of dataBlocks) {
      const codeword = block[i];
      if (codeword !== undefined) result.push(codeword);
    }
  }
  for (let i = 0; i < ecPerBlock; i++) {
    for (const block of ecBlocks) {
      const codeword = block[i];
      if (codeword !== undefined) result.push(codeword);
    }
  }
  return result;
}

// --- Matrix ----------------------------------------------------------------
//
// The symbol is held as flat typed arrays rather than arrays of arrays. Indexing
// a `Uint8Array` yields a number rather than `number | undefined`, so the
// placement code below reads as the specification does — without an assertion on
// every access to say what the loop bounds already guarantee.

/** Module states: 0 light, 1 dark, 2 not yet placed. */
const UNSET = 2;

interface Symbol_ {
  readonly size: number;
  /** Module state per cell. */
  readonly grid: Uint8Array;
  /** 1 where a function pattern owns the cell and data may not go. */
  readonly reserved: Uint8Array;
}

function placeFinder(symbol: Symbol_, row: number, col: number): void {
  const { size, grid, reserved } = symbol;

  for (let r = -1; r <= 7; r++) {
    for (let c = -1; c <= 7; c++) {
      const y = row + r;
      const x = col + c;
      if (y < 0 || y >= size || x < 0 || x >= size) continue;

      const inRing =
        (r >= 0 && r <= 6 && (c === 0 || c === 6)) || (c >= 0 && c <= 6 && (r === 0 || r === 6));
      const inCore = r >= 2 && r <= 4 && c >= 2 && c <= 4;
      grid[y * size + x] = inRing || inCore ? 1 : 0;
      reserved[y * size + x] = 1;
    }
  }
}

function buildFunctionPatterns(version: number): Symbol_ {
  const size = version * 4 + 17;
  const symbol: Symbol_ = {
    size,
    grid: new Uint8Array(size * size).fill(UNSET),
    reserved: new Uint8Array(size * size),
  };
  const { grid, reserved } = symbol;
  const at = (row: number, col: number) => row * size + col;

  placeFinder(symbol, 0, 0);
  placeFinder(symbol, 0, size - 7);
  placeFinder(symbol, size - 7, 0);

  // Timing patterns.
  for (let i = 8; i < size - 8; i++) {
    const value = i % 2 === 0 ? 1 : 0;
    grid[at(6, i)] = value;
    grid[at(i, 6)] = value;
    reserved[at(6, i)] = 1;
    reserved[at(i, 6)] = 1;
  }

  // Alignment patterns, skipping the three that would collide with finders.
  const centres = ALIGNMENT[version - 1] ?? [];
  for (const row of centres) {
    for (const col of centres) {
      const nearFinder =
        (row === 6 && col === 6) ||
        (row === 6 && col === size - 7) ||
        (row === size - 7 && col === 6);
      if (nearFinder) continue;

      for (let r = -2; r <= 2; r++) {
        for (let c = -2; c <= 2; c++) {
          grid[at(row + r, col + c)] = Math.max(Math.abs(r), Math.abs(c)) !== 1 ? 1 : 0;
          reserved[at(row + r, col + c)] = 1;
        }
      }
    }
  }

  // The dark module, always set, always here.
  grid[at(size - 8, 8)] = 1;
  reserved[at(size - 8, 8)] = 1;

  // Reserve the format-information areas.
  for (let i = 0; i < 9; i++) {
    reserved[at(8, i)] = 1;
    reserved[at(i, 8)] = 1;
  }
  for (let i = 0; i < 8; i++) {
    reserved[at(8, size - 1 - i)] = 1;
    reserved[at(size - 1 - i, 8)] = 1;
  }

  // Version information, for versions 7 and up.
  if (version >= 7) {
    const bits = versionInformation(version);
    for (let i = 0; i < 18; i++) {
      const bit = (bits >> i) & 1;
      const row = Math.floor(i / 3);
      const col = size - 11 + (i % 3);
      grid[at(row, col)] = bit;
      reserved[at(row, col)] = 1;
      grid[at(col, row)] = bit;
      reserved[at(col, row)] = 1;
    }
  }

  return symbol;
}

/** BCH(18,6) — the version bits plus their check bits. */
function versionInformation(version: number): number {
  let remainder = version;
  for (let i = 0; i < 12; i++) {
    remainder = (remainder << 1) ^ ((remainder >> 11) * 0x1f25);
  }
  return (version << 12) | remainder;
}

/** BCH(15,5) over the level and mask, masked with 0x5412 as specified. */
function formatInformation(mask: number): number {
  // 0b00 is the two-bit code for level M.
  const data = (0b00 << 3) | mask;
  let remainder = data;
  for (let i = 0; i < 10; i++) {
    remainder = (remainder << 1) ^ ((remainder >> 9) * 0x537);
  }
  return ((data << 10) | remainder) ^ 0x5412;
}

function placeFormat(symbol: Symbol_, mask: number): void {
  const { size, grid } = symbol;
  const bits = formatInformation(mask);
  const at = (row: number, col: number) => row * size + col;

  // Bit 0 is the least significant. The two copies run in opposite directions,
  // which is the detail worth stating rather than deriving: copy A climbs the
  // column beside the top-left finder and continues up from the bottom-left
  // one; copy B runs leftwards along row 8 from the right edge.
  for (let i = 0; i < 15; i++) {
    const bit = (bits >> i) & 1;

    // Copy A — vertical.
    if (i < 6) grid[at(i, 8)] = bit;
    else if (i < 8) grid[at(i + 1, 8)] = bit;
    else grid[at(size - 15 + i, 8)] = bit;

    // Copy B — horizontal.
    if (i < 8) grid[at(8, size - 1 - i)] = bit;
    else if (i === 8) grid[at(8, 15 - i)] = bit;
    else grid[at(8, 14 - i)] = bit;
  }
}

function maskAt(mask: number, row: number, col: number): boolean {
  switch (mask) {
    case 0:
      return (row + col) % 2 === 0;
    case 1:
      return row % 2 === 0;
    case 2:
      return col % 3 === 0;
    case 3:
      return (row + col) % 3 === 0;
    case 4:
      return (Math.floor(row / 2) + Math.floor(col / 3)) % 2 === 0;
    case 5:
      return ((row * col) % 2) + ((row * col) % 3) === 0;
    case 6:
      return (((row * col) % 2) + ((row * col) % 3)) % 2 === 0;
    default:
      return (((row + col) % 2) + ((row * col) % 3)) % 2 === 0;
  }
}

/** Zigzag placement, right to left in two-module columns, skipping column 6. */
function placeData(symbol: Symbol_, codewords: readonly number[]): void {
  const { size, grid, reserved } = symbol;
  let bitIndex = 0;
  let upward = true;

  for (let right = size - 1; right >= 1; right -= 2) {
    if (right === 6) right = 5; // the vertical timing pattern

    for (let step = 0; step < size; step++) {
      const row = upward ? size - 1 - step : step;
      for (const col of [right, right - 1]) {
        const index = row * size + col;
        if (reserved[index]) continue;

        const byte = codewords[bitIndex >>> 3];
        grid[index] = byte === undefined ? 0 : (byte >> (7 - (bitIndex & 7))) & 1;
        bitIndex++;
      }
    }
    upward = !upward;
  }
}

/** The specification's penalty score; the lowest-scoring mask wins. */
function penalty(modules: readonly (readonly boolean[])[]): number {
  const size = modules.length;
  let score = 0;

  // Rule 1: runs of five or more of the same colour.
  const runScore = (get: (i: number, j: number) => boolean) => {
    for (let i = 0; i < size; i++) {
      let run = 1;
      for (let j = 1; j < size; j++) {
        if (get(i, j) === get(i, j - 1)) {
          run++;
        } else {
          if (run >= 5) score += run - 2;
          run = 1;
        }
      }
      if (run >= 5) score += run - 2;
    }
  };
  runScore((i, j) => modules[i]![j]!);
  runScore((i, j) => modules[j]![i]!);

  // Rule 2: 2×2 blocks of one colour.
  for (let r = 0; r < size - 1; r++) {
    for (let c = 0; c < size - 1; c++) {
      const first = modules[r]![c]!;
      if (
        first === modules[r]![c + 1] &&
        first === modules[r + 1]![c] &&
        first === modules[r + 1]![c + 1]
      ) {
        score += 3;
      }
    }
  }

  // Rule 3: the finder-like 1:1:3:1:1 pattern with four light modules beside it.
  const pattern = [true, false, true, true, true, false, true];
  const matches = (get: (k: number) => boolean, start: number): boolean => {
    for (let k = 0; k < 7; k++) if (get(start + k) !== pattern[k]) return false;
    return true;
  };
  const light = (get: (k: number) => boolean, from: number, to: number): boolean => {
    for (let k = from; k < to; k++) {
      if (k >= 0 && k < size && get(k)) return false;
    }
    return true;
  };
  for (let i = 0; i < size; i++) {
    for (const get of [(k: number) => modules[i]![k]!, (k: number) => modules[k]![i]!]) {
      for (let j = 0; j <= size - 7; j++) {
        if (!matches(get, j)) continue;
        if (light(get, j - 4, j) || light(get, j + 7, j + 11)) score += 40;
      }
    }
  }

  // Rule 4: deviation from an even balance of dark and light.
  let dark = 0;
  for (const row of modules) for (const cell of row) if (cell) dark++;
  const percent = (dark * 100) / (size * size);
  score += Math.floor(Math.abs(percent - 50) / 5) * 10;

  return score;
}

export interface QrCode {
  /** Row-major modules; `true` is dark. */
  readonly modules: readonly (readonly boolean[])[];
  readonly size: number;
  readonly version: number;
}

/**
 * Encodes text as a QR symbol, or returns null when it will not fit.
 *
 * Null rather than throwing: the caller's response to "this URL is too long"
 * is to not show a QR, which is not an error condition.
 */
export function encodeQr(text: string): QrCode | null {
  const bytes = new TextEncoder().encode(text);
  const version = chooseVersion(bytes.length);
  if (version === null) return null;

  const codewords = interleave(encodeData(bytes, version), version);

  let best: boolean[][] | null = null;
  let bestScore = Infinity;

  for (let mask = 0; mask < 8; mask++) {
    const symbol = buildFunctionPatterns(version);
    placeData(symbol, codewords);
    placeFormat(symbol, mask);

    const { size, grid, reserved } = symbol;
    const modules: boolean[][] = [];
    for (let row = 0; row < size; row++) {
      const line: boolean[] = [];
      for (let col = 0; col < size; col++) {
        const index = row * size + col;
        const value = grid[index] === 1;
        // Function patterns are never masked.
        line.push(reserved[index] ? value : value !== maskAt(mask, row, col));
      }
      modules.push(line);
    }

    const score = penalty(modules);
    if (score < bestScore) {
      bestScore = score;
      best = modules;
    }
  }

  // Eight masks are always evaluated, so `best` is set by here; the check keeps
  // that a fact rather than an assertion.
  if (!best) return null;
  return { modules: best, size: best.length, version };
}
