/**
 * Countries and the currency each one uses.
 *
 * GENERATED by scripts/generate-countries.mjs. Do not edit by hand.
 *
 * Travelers think in countries, not currency codes — you know you are going to
 * Japan, not that you need JPY (ADR-014). This table is what lets the app ask
 * the question the user can actually answer.
 *
 * The country → currency mapping is curated (no API provides it); Spanish names
 * come from ICU and flags are computed from the country code. Unlike exchange
 * rates, this is stable reference data a reviewer can verify row by row.
 */

import type { CurrencyCode } from './currencies';

export interface Country {
  /** ISO 3166-1 alpha-2. */
  readonly code: string;
  /** Display name in Spanish (CLDR). */
  readonly name: string;
  /** The currency a traveler will actually pay with there. */
  readonly currency: CurrencyCode;
  /** Emoji flag, derived from the country code. */
  readonly flag: string;
}

export const COUNTRIES: readonly Country[] = [
  { code: 'AF', name: 'Afganistán', currency: 'AFN', flag: '🇦🇫' },
  { code: 'AL', name: 'Albania', currency: 'ALL', flag: '🇦🇱' },
  { code: 'DE', name: 'Alemania', currency: 'EUR', flag: '🇩🇪' },
  { code: 'AD', name: 'Andorra', currency: 'EUR', flag: '🇦🇩' },
  { code: 'AO', name: 'Angola', currency: 'AOA', flag: '🇦🇴' },
  { code: 'AG', name: 'Antigua y Barbuda', currency: 'XCD', flag: '🇦🇬' },
  { code: 'SA', name: 'Arabia Saudí', currency: 'SAR', flag: '🇸🇦' },
  { code: 'DZ', name: 'Argelia', currency: 'DZD', flag: '🇩🇿' },
  { code: 'AR', name: 'Argentina', currency: 'ARS', flag: '🇦🇷' },
  { code: 'AM', name: 'Armenia', currency: 'AMD', flag: '🇦🇲' },
  { code: 'AW', name: 'Aruba', currency: 'AWG', flag: '🇦🇼' },
  { code: 'AU', name: 'Australia', currency: 'AUD', flag: '🇦🇺' },
  { code: 'AT', name: 'Austria', currency: 'EUR', flag: '🇦🇹' },
  { code: 'AZ', name: 'Azerbaiyán', currency: 'AZN', flag: '🇦🇿' },
  { code: 'BS', name: 'Bahamas', currency: 'BSD', flag: '🇧🇸' },
  { code: 'BD', name: 'Bangladés', currency: 'BDT', flag: '🇧🇩' },
  { code: 'BB', name: 'Barbados', currency: 'BBD', flag: '🇧🇧' },
  { code: 'BH', name: 'Baréin', currency: 'BHD', flag: '🇧🇭' },
  { code: 'BE', name: 'Bélgica', currency: 'EUR', flag: '🇧🇪' },
  { code: 'BZ', name: 'Belice', currency: 'BZD', flag: '🇧🇿' },
  { code: 'BJ', name: 'Benín', currency: 'XOF', flag: '🇧🇯' },
  { code: 'BM', name: 'Bermudas', currency: 'BMD', flag: '🇧🇲' },
  { code: 'BY', name: 'Bielorrusia', currency: 'BYN', flag: '🇧🇾' },
  { code: 'BO', name: 'Bolivia', currency: 'BOB', flag: '🇧🇴' },
  { code: 'BA', name: 'Bosnia y Herzegovina', currency: 'BAM', flag: '🇧🇦' },
  { code: 'BW', name: 'Botsuana', currency: 'BWP', flag: '🇧🇼' },
  { code: 'BR', name: 'Brasil', currency: 'BRL', flag: '🇧🇷' },
  { code: 'BN', name: 'Brunéi', currency: 'BND', flag: '🇧🇳' },
  { code: 'BG', name: 'Bulgaria', currency: 'EUR', flag: '🇧🇬' },
  { code: 'BF', name: 'Burkina Faso', currency: 'XOF', flag: '🇧🇫' },
  { code: 'BI', name: 'Burundi', currency: 'BIF', flag: '🇧🇮' },
  { code: 'BT', name: 'Bután', currency: 'BTN', flag: '🇧🇹' },
  { code: 'CV', name: 'Cabo Verde', currency: 'CVE', flag: '🇨🇻' },
  { code: 'KH', name: 'Camboya', currency: 'KHR', flag: '🇰🇭' },
  { code: 'CM', name: 'Camerún', currency: 'XAF', flag: '🇨🇲' },
  { code: 'CA', name: 'Canadá', currency: 'CAD', flag: '🇨🇦' },
  { code: 'QA', name: 'Catar', currency: 'QAR', flag: '🇶🇦' },
  { code: 'TD', name: 'Chad', currency: 'XAF', flag: '🇹🇩' },
  { code: 'CZ', name: 'Chequia', currency: 'CZK', flag: '🇨🇿' },
  { code: 'CL', name: 'Chile', currency: 'CLP', flag: '🇨🇱' },
  { code: 'CN', name: 'China', currency: 'CNY', flag: '🇨🇳' },
  { code: 'CY', name: 'Chipre', currency: 'EUR', flag: '🇨🇾' },
  { code: 'VA', name: 'Ciudad del Vaticano', currency: 'EUR', flag: '🇻🇦' },
  { code: 'CO', name: 'Colombia', currency: 'COP', flag: '🇨🇴' },
  { code: 'KM', name: 'Comoras', currency: 'KMF', flag: '🇰🇲' },
  { code: 'CG', name: 'Congo', currency: 'XAF', flag: '🇨🇬' },
  { code: 'KP', name: 'Corea del Norte', currency: 'KPW', flag: '🇰🇵' },
  { code: 'KR', name: 'Corea del Sur', currency: 'KRW', flag: '🇰🇷' },
  { code: 'CR', name: 'Costa Rica', currency: 'CRC', flag: '🇨🇷' },
  { code: 'CI', name: 'Côte d’Ivoire', currency: 'XOF', flag: '🇨🇮' },
  { code: 'HR', name: 'Croacia', currency: 'EUR', flag: '🇭🇷' },
  { code: 'CU', name: 'Cuba', currency: 'CUP', flag: '🇨🇺' },
  { code: 'DK', name: 'Dinamarca', currency: 'DKK', flag: '🇩🇰' },
  { code: 'DM', name: 'Dominica', currency: 'XCD', flag: '🇩🇲' },
  { code: 'EC', name: 'Ecuador', currency: 'USD', flag: '🇪🇨' },
  { code: 'EG', name: 'Egipto', currency: 'EGP', flag: '🇪🇬' },
  { code: 'SV', name: 'El Salvador', currency: 'USD', flag: '🇸🇻' },
  { code: 'AE', name: 'Emiratos Árabes Unidos', currency: 'AED', flag: '🇦🇪' },
  { code: 'ER', name: 'Eritrea', currency: 'ERN', flag: '🇪🇷' },
  { code: 'SK', name: 'Eslovaquia', currency: 'EUR', flag: '🇸🇰' },
  { code: 'SI', name: 'Eslovenia', currency: 'EUR', flag: '🇸🇮' },
  { code: 'ES', name: 'España', currency: 'EUR', flag: '🇪🇸' },
  { code: 'US', name: 'Estados Unidos', currency: 'USD', flag: '🇺🇸' },
  { code: 'EE', name: 'Estonia', currency: 'EUR', flag: '🇪🇪' },
  { code: 'SZ', name: 'Esuatini', currency: 'SZL', flag: '🇸🇿' },
  { code: 'ET', name: 'Etiopía', currency: 'ETB', flag: '🇪🇹' },
  { code: 'PH', name: 'Filipinas', currency: 'PHP', flag: '🇵🇭' },
  { code: 'FI', name: 'Finlandia', currency: 'EUR', flag: '🇫🇮' },
  { code: 'FJ', name: 'Fiyi', currency: 'FJD', flag: '🇫🇯' },
  { code: 'FR', name: 'Francia', currency: 'EUR', flag: '🇫🇷' },
  { code: 'GA', name: 'Gabón', currency: 'XAF', flag: '🇬🇦' },
  { code: 'GM', name: 'Gambia', currency: 'GMD', flag: '🇬🇲' },
  { code: 'GE', name: 'Georgia', currency: 'GEL', flag: '🇬🇪' },
  { code: 'GH', name: 'Ghana', currency: 'GHS', flag: '🇬🇭' },
  { code: 'GI', name: 'Gibraltar', currency: 'GIP', flag: '🇬🇮' },
  { code: 'GD', name: 'Granada', currency: 'XCD', flag: '🇬🇩' },
  { code: 'GR', name: 'Grecia', currency: 'EUR', flag: '🇬🇷' },
  { code: 'GT', name: 'Guatemala', currency: 'GTQ', flag: '🇬🇹' },
  { code: 'GN', name: 'Guinea', currency: 'GNF', flag: '🇬🇳' },
  { code: 'GQ', name: 'Guinea Ecuatorial', currency: 'XAF', flag: '🇬🇶' },
  { code: 'GW', name: 'Guinea-Bisáu', currency: 'XOF', flag: '🇬🇼' },
  { code: 'GY', name: 'Guyana', currency: 'GYD', flag: '🇬🇾' },
  { code: 'HT', name: 'Haití', currency: 'HTG', flag: '🇭🇹' },
  { code: 'HN', name: 'Honduras', currency: 'HNL', flag: '🇭🇳' },
  { code: 'HU', name: 'Hungría', currency: 'HUF', flag: '🇭🇺' },
  { code: 'IN', name: 'India', currency: 'INR', flag: '🇮🇳' },
  { code: 'ID', name: 'Indonesia', currency: 'IDR', flag: '🇮🇩' },
  { code: 'IQ', name: 'Irak', currency: 'IQD', flag: '🇮🇶' },
  { code: 'IR', name: 'Irán', currency: 'IRR', flag: '🇮🇷' },
  { code: 'IE', name: 'Irlanda', currency: 'EUR', flag: '🇮🇪' },
  { code: 'IS', name: 'Islandia', currency: 'ISK', flag: '🇮🇸' },
  { code: 'KY', name: 'Islas Caimán', currency: 'KYD', flag: '🇰🇾' },
  { code: 'FK', name: 'Islas Malvinas', currency: 'FKP', flag: '🇫🇰' },
  { code: 'SB', name: 'Islas Salomón', currency: 'SBD', flag: '🇸🇧' },
  { code: 'IL', name: 'Israel', currency: 'ILS', flag: '🇮🇱' },
  { code: 'IT', name: 'Italia', currency: 'EUR', flag: '🇮🇹' },
  { code: 'JM', name: 'Jamaica', currency: 'JMD', flag: '🇯🇲' },
  { code: 'JP', name: 'Japón', currency: 'JPY', flag: '🇯🇵' },
  { code: 'JO', name: 'Jordania', currency: 'JOD', flag: '🇯🇴' },
  { code: 'KZ', name: 'Kazajistán', currency: 'KZT', flag: '🇰🇿' },
  { code: 'KE', name: 'Kenia', currency: 'KES', flag: '🇰🇪' },
  { code: 'KG', name: 'Kirguistán', currency: 'KGS', flag: '🇰🇬' },
  { code: 'KW', name: 'Kuwait', currency: 'KWD', flag: '🇰🇼' },
  { code: 'LA', name: 'Laos', currency: 'LAK', flag: '🇱🇦' },
  { code: 'LS', name: 'Lesoto', currency: 'LSL', flag: '🇱🇸' },
  { code: 'LV', name: 'Letonia', currency: 'EUR', flag: '🇱🇻' },
  { code: 'LB', name: 'Líbano', currency: 'LBP', flag: '🇱🇧' },
  { code: 'LR', name: 'Liberia', currency: 'LRD', flag: '🇱🇷' },
  { code: 'LY', name: 'Libia', currency: 'LYD', flag: '🇱🇾' },
  { code: 'LI', name: 'Liechtenstein', currency: 'CHF', flag: '🇱🇮' },
  { code: 'LT', name: 'Lituania', currency: 'EUR', flag: '🇱🇹' },
  { code: 'LU', name: 'Luxemburgo', currency: 'EUR', flag: '🇱🇺' },
  { code: 'MK', name: 'Macedonia del Norte', currency: 'MKD', flag: '🇲🇰' },
  { code: 'MG', name: 'Madagascar', currency: 'MGA', flag: '🇲🇬' },
  { code: 'MY', name: 'Malasia', currency: 'MYR', flag: '🇲🇾' },
  { code: 'MW', name: 'Malaui', currency: 'MWK', flag: '🇲🇼' },
  { code: 'MV', name: 'Maldivas', currency: 'MVR', flag: '🇲🇻' },
  { code: 'MT', name: 'Malta', currency: 'EUR', flag: '🇲🇹' },
  { code: 'MA', name: 'Marruecos', currency: 'MAD', flag: '🇲🇦' },
  { code: 'MU', name: 'Mauricio', currency: 'MUR', flag: '🇲🇺' },
  { code: 'MR', name: 'Mauritania', currency: 'MRU', flag: '🇲🇷' },
  { code: 'MX', name: 'México', currency: 'MXN', flag: '🇲🇽' },
  { code: 'MD', name: 'Moldavia', currency: 'MDL', flag: '🇲🇩' },
  { code: 'MC', name: 'Mónaco', currency: 'EUR', flag: '🇲🇨' },
  { code: 'MN', name: 'Mongolia', currency: 'MNT', flag: '🇲🇳' },
  { code: 'ME', name: 'Montenegro', currency: 'EUR', flag: '🇲🇪' },
  { code: 'MZ', name: 'Mozambique', currency: 'MZN', flag: '🇲🇿' },
  { code: 'MM', name: 'Myanmar (Birmania)', currency: 'MMK', flag: '🇲🇲' },
  { code: 'NA', name: 'Namibia', currency: 'NAD', flag: '🇳🇦' },
  { code: 'NP', name: 'Nepal', currency: 'NPR', flag: '🇳🇵' },
  { code: 'NI', name: 'Nicaragua', currency: 'NIO', flag: '🇳🇮' },
  { code: 'NE', name: 'Níger', currency: 'XOF', flag: '🇳🇪' },
  { code: 'NG', name: 'Nigeria', currency: 'NGN', flag: '🇳🇬' },
  { code: 'NO', name: 'Noruega', currency: 'NOK', flag: '🇳🇴' },
  { code: 'NZ', name: 'Nueva Zelanda', currency: 'NZD', flag: '🇳🇿' },
  { code: 'OM', name: 'Omán', currency: 'OMR', flag: '🇴🇲' },
  { code: 'NL', name: 'Países Bajos', currency: 'EUR', flag: '🇳🇱' },
  { code: 'PK', name: 'Pakistán', currency: 'PKR', flag: '🇵🇰' },
  { code: 'PA', name: 'Panamá', currency: 'PAB', flag: '🇵🇦' },
  { code: 'PG', name: 'Papúa Nueva Guinea', currency: 'PGK', flag: '🇵🇬' },
  { code: 'PY', name: 'Paraguay', currency: 'PYG', flag: '🇵🇾' },
  { code: 'PE', name: 'Perú', currency: 'PEN', flag: '🇵🇪' },
  { code: 'PF', name: 'Polinesia Francesa', currency: 'XPF', flag: '🇵🇫' },
  { code: 'PL', name: 'Polonia', currency: 'PLN', flag: '🇵🇱' },
  { code: 'PT', name: 'Portugal', currency: 'EUR', flag: '🇵🇹' },
  { code: 'HK', name: 'RAE de Hong Kong (China)', currency: 'HKD', flag: '🇭🇰' },
  { code: 'MO', name: 'RAE de Macao (China)', currency: 'MOP', flag: '🇲🇴' },
  { code: 'GB', name: 'Reino Unido', currency: 'GBP', flag: '🇬🇧' },
  { code: 'CF', name: 'República Centroafricana', currency: 'XAF', flag: '🇨🇫' },
  { code: 'CD', name: 'República Democrática del Congo', currency: 'CDF', flag: '🇨🇩' },
  { code: 'DO', name: 'República Dominicana', currency: 'DOP', flag: '🇩🇴' },
  { code: 'RW', name: 'Ruanda', currency: 'RWF', flag: '🇷🇼' },
  { code: 'RO', name: 'Rumanía', currency: 'RON', flag: '🇷🇴' },
  { code: 'RU', name: 'Rusia', currency: 'RUB', flag: '🇷🇺' },
  { code: 'WS', name: 'Samoa', currency: 'WST', flag: '🇼🇸' },
  { code: 'SM', name: 'San Marino', currency: 'EUR', flag: '🇸🇲' },
  { code: 'SH', name: 'Santa Elena', currency: 'SHP', flag: '🇸🇭' },
  { code: 'LC', name: 'Santa Lucía', currency: 'XCD', flag: '🇱🇨' },
  { code: 'ST', name: 'Santo Tomé y Príncipe', currency: 'STN', flag: '🇸🇹' },
  { code: 'SN', name: 'Senegal', currency: 'XOF', flag: '🇸🇳' },
  { code: 'RS', name: 'Serbia', currency: 'RSD', flag: '🇷🇸' },
  { code: 'SC', name: 'Seychelles', currency: 'SCR', flag: '🇸🇨' },
  { code: 'SL', name: 'Sierra Leona', currency: 'SLE', flag: '🇸🇱' },
  { code: 'SG', name: 'Singapur', currency: 'SGD', flag: '🇸🇬' },
  { code: 'SY', name: 'Siria', currency: 'SYP', flag: '🇸🇾' },
  { code: 'SO', name: 'Somalia', currency: 'SOS', flag: '🇸🇴' },
  { code: 'LK', name: 'Sri Lanka', currency: 'LKR', flag: '🇱🇰' },
  { code: 'ZA', name: 'Sudáfrica', currency: 'ZAR', flag: '🇿🇦' },
  { code: 'SD', name: 'Sudán', currency: 'SDG', flag: '🇸🇩' },
  { code: 'SS', name: 'Sudán del Sur', currency: 'SSP', flag: '🇸🇸' },
  { code: 'SE', name: 'Suecia', currency: 'SEK', flag: '🇸🇪' },
  { code: 'CH', name: 'Suiza', currency: 'CHF', flag: '🇨🇭' },
  { code: 'SR', name: 'Surinam', currency: 'SRD', flag: '🇸🇷' },
  { code: 'TH', name: 'Tailandia', currency: 'THB', flag: '🇹🇭' },
  { code: 'TW', name: 'Taiwán', currency: 'TWD', flag: '🇹🇼' },
  { code: 'TZ', name: 'Tanzania', currency: 'TZS', flag: '🇹🇿' },
  { code: 'TJ', name: 'Tayikistán', currency: 'TJS', flag: '🇹🇯' },
  { code: 'TL', name: 'Timor-Leste', currency: 'USD', flag: '🇹🇱' },
  { code: 'TG', name: 'Togo', currency: 'XOF', flag: '🇹🇬' },
  { code: 'TO', name: 'Tonga', currency: 'TOP', flag: '🇹🇴' },
  { code: 'TT', name: 'Trinidad y Tobago', currency: 'TTD', flag: '🇹🇹' },
  { code: 'TN', name: 'Túnez', currency: 'TND', flag: '🇹🇳' },
  { code: 'TM', name: 'Turkmenistán', currency: 'TMT', flag: '🇹🇲' },
  { code: 'TR', name: 'Turquía', currency: 'TRY', flag: '🇹🇷' },
  { code: 'UA', name: 'Ucrania', currency: 'UAH', flag: '🇺🇦' },
  { code: 'UG', name: 'Uganda', currency: 'UGX', flag: '🇺🇬' },
  { code: 'UY', name: 'Uruguay', currency: 'UYU', flag: '🇺🇾' },
  { code: 'UZ', name: 'Uzbekistán', currency: 'UZS', flag: '🇺🇿' },
  { code: 'VU', name: 'Vanuatu', currency: 'VUV', flag: '🇻🇺' },
  { code: 'VE', name: 'Venezuela', currency: 'VES', flag: '🇻🇪' },
  { code: 'VN', name: 'Vietnam', currency: 'VND', flag: '🇻🇳' },
  { code: 'YE', name: 'Yemen', currency: 'YER', flag: '🇾🇪' },
  { code: 'DJ', name: 'Yibuti', currency: 'DJF', flag: '🇩🇯' },
  { code: 'ZM', name: 'Zambia', currency: 'ZMW', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabue', currency: 'ZWG', flag: '🇿🇼' },
];

/**
 * The country shown to represent a currency — needed after a swap, when the UI
 * has a currency and must display a country for it.
 *
 * Several countries share a currency (twenty use the euro), so the choice is
 * explicit for those and falls back to the first match otherwise.
 */
const PRIMARY_BY_CURRENCY: Readonly<Record<string, string>> = {
  EUR: 'ES',
  USD: 'US',
  XOF: 'SN',
  XAF: 'CM',
  XCD: 'AG',
  CHF: 'CH',
  XPF: 'PF',
};

const BY_CODE: ReadonlyMap<string, Country> = new Map(COUNTRIES.map((c) => [c.code, c]));

export function getCountry(code: string): Country | undefined {
  return BY_CODE.get(code);
}

/** The representative country for a currency, or undefined if none uses it. */
export function countryForCurrency(currency: CurrencyCode): Country | undefined {
  const preferred = PRIMARY_BY_CURRENCY[currency];
  if (preferred) {
    const country = BY_CODE.get(preferred);
    if (country) return country;
  }
  return COUNTRIES.find((c) => c.currency === currency);
}
