/**
 * Currency metadata — the single source of truth for every currency in PriceLens.
 *
 * GENERATED by scripts/generate-currencies.mjs from ICU/CLDR data. Do not edit by
 * hand: run `node scripts/generate-currencies.mjs` and commit the result.
 * Hand-maintained currency tables drift from reality and get minor units wrong.
 *
 * `digits` is read from `Intl.NumberFormat(...).resolvedOptions()`, which means it
 * always agrees with how we actually render the value. Note this follows CLDR's
 * practical minor units rather than ISO 4217's nominal ones — e.g. CLDR treats ALL
 * and IQD as zero-decimal because they are not subdivided in practice. Agreeing with
 * the formatter is what matters: rounding and display can never disagree.
 *
 * See docs/ARCHITECTURE.md ADR-006.
 */

export interface CurrencyMeta {
  /** ISO 4217 alphabetic code. */
  readonly code: string;
  /** Display name in Spanish (CLDR). */
  readonly name: string;
  /** Narrow symbol, falling back to the code where CLDR has no symbol. */
  readonly symbol: string;
  /** Minor-unit digits used for rounding AND display. */
  readonly digits: number;
  /** Country or territory, so travelers can search "Japón" instead of "JPY". */
  readonly region: string;
}

export const CURRENCIES = [
  {
    code: 'AED',
    name: 'dírham de los Emiratos Árabes Unidos',
    symbol: 'AED',
    digits: 2,
    region: 'Emiratos Árabes Unidos',
  },
  { code: 'AFN', name: 'afgani afgano', symbol: '؋', digits: 0, region: 'Afganistán' },
  { code: 'ALL', name: 'lek albanés', symbol: 'ALL', digits: 0, region: 'Albania' },
  { code: 'AMD', name: 'dram armenio', symbol: '֏', digits: 2, region: 'Armenia' },
  { code: 'ANG', name: 'florín antillano', symbol: 'ANG', digits: 2, region: 'Caribe Neerlandés' },
  { code: 'AOA', name: 'kuanza angoleño', symbol: 'Kz', digits: 2, region: 'Angola' },
  { code: 'ARS', name: 'peso argentino', symbol: '$', digits: 2, region: 'Argentina' },
  { code: 'AUD', name: 'dólar australiano', symbol: '$', digits: 2, region: 'Australia' },
  { code: 'AWG', name: 'florín arubeño', symbol: 'AWG', digits: 2, region: 'Aruba' },
  { code: 'AZN', name: 'manat azerbaiyano', symbol: '₼', digits: 2, region: 'Azerbaiyán' },
  {
    code: 'BAM',
    name: 'marco convertible de Bosnia y Herzegovina',
    symbol: 'KM',
    digits: 2,
    region: 'Bosnia y Herzegovina',
  },
  { code: 'BBD', name: 'dólar barbadense', symbol: '$', digits: 2, region: 'Barbados' },
  { code: 'BDT', name: 'taka bangladesí', symbol: '৳', digits: 2, region: 'Bangladés' },
  { code: 'BGN', name: 'leva búlgara', symbol: 'BGN', digits: 2, region: 'Bulgaria' },
  { code: 'BHD', name: 'dinar bareiní', symbol: 'BHD', digits: 3, region: 'Baréin' },
  { code: 'BIF', name: 'franco burundés', symbol: 'BIF', digits: 0, region: 'Burundi' },
  { code: 'BMD', name: 'dólar bermudeño', symbol: '$', digits: 2, region: 'Bermudas' },
  { code: 'BND', name: 'dólar bruneano', symbol: '$', digits: 2, region: 'Brunéi' },
  { code: 'BOB', name: 'boliviano', symbol: 'Bs', digits: 2, region: 'Bolivia' },
  { code: 'BRL', name: 'real brasileño', symbol: 'R$', digits: 2, region: 'Brasil' },
  { code: 'BSD', name: 'dólar bahameño', symbol: '$', digits: 2, region: 'Bahamas' },
  { code: 'BTN', name: 'gultrum butanés', symbol: 'BTN', digits: 2, region: 'Bután' },
  { code: 'BWP', name: 'pula botsuano', symbol: 'P', digits: 2, region: 'Botsuana' },
  { code: 'BYN', name: 'rublo bielorruso', symbol: 'р.', digits: 2, region: 'Bielorrusia' },
  { code: 'BZD', name: 'dólar beliceño', symbol: '$', digits: 2, region: 'Belice' },
  { code: 'CAD', name: 'dólar canadiense', symbol: '$', digits: 2, region: 'Canadá' },
  {
    code: 'CDF',
    name: 'franco congoleño',
    symbol: 'CDF',
    digits: 2,
    region: 'República Democrática del Congo',
  },
  { code: 'CHF', name: 'franco suizo', symbol: 'CHF', digits: 2, region: 'Suiza' },
  { code: 'CLP', name: 'peso chileno', symbol: '$', digits: 0, region: 'Chile' },
  { code: 'CNY', name: 'yuan renminbi', symbol: '¥', digits: 2, region: 'China' },
  { code: 'COP', name: 'peso colombiano', symbol: '$', digits: 0, region: 'Colombia' },
  { code: 'CRC', name: 'colón costarricense', symbol: '₡', digits: 2, region: 'Costa Rica' },
  { code: 'CUP', name: 'peso cubano', symbol: '$', digits: 2, region: 'Cuba' },
  { code: 'CVE', name: 'escudo de Cabo Verde', symbol: 'CVE', digits: 2, region: 'Cabo Verde' },
  { code: 'CZK', name: 'corona checa', symbol: 'Kč', digits: 2, region: 'Chequia' },
  { code: 'DJF', name: 'franco yibutiano', symbol: 'DJF', digits: 0, region: 'Yibuti' },
  { code: 'DKK', name: 'corona danesa', symbol: 'kr', digits: 2, region: 'Dinamarca' },
  { code: 'DOP', name: 'peso dominicano', symbol: '$', digits: 2, region: 'República Dominicana' },
  { code: 'DZD', name: 'dinar argelino', symbol: 'DZD', digits: 2, region: 'Argelia' },
  { code: 'EGP', name: 'libra egipcia', symbol: 'EGP', digits: 2, region: 'Egipto' },
  { code: 'ERN', name: 'nakfa eritreo', symbol: 'ERN', digits: 2, region: 'Eritrea' },
  { code: 'ETB', name: 'bir etíope', symbol: 'ETB', digits: 2, region: 'Etiopía' },
  { code: 'EUR', name: 'euro', symbol: '€', digits: 2, region: 'Zona euro' },
  { code: 'FJD', name: 'dólar fiyiano', symbol: '$', digits: 2, region: 'Fiyi' },
  { code: 'FKP', name: 'libra malvinense', symbol: '£', digits: 2, region: 'Islas Malvinas' },
  { code: 'GBP', name: 'libra esterlina', symbol: '£', digits: 2, region: 'Reino Unido' },
  { code: 'GEL', name: 'lari georgiano', symbol: '₾', digits: 2, region: 'Georgia' },
  { code: 'GHS', name: 'cedi ghanés', symbol: 'GH₵', digits: 2, region: 'Ghana' },
  { code: 'GIP', name: 'libra gibraltareña', symbol: '£', digits: 2, region: 'Gibraltar' },
  { code: 'GMD', name: 'dalasi gambiano', symbol: 'GMD', digits: 2, region: 'Gambia' },
  { code: 'GNF', name: 'franco guineano', symbol: 'FG', digits: 0, region: 'Guinea' },
  { code: 'GTQ', name: 'quetzal guatemalteco', symbol: 'Q', digits: 2, region: 'Guatemala' },
  { code: 'GYD', name: 'dólar guyanés', symbol: '$', digits: 2, region: 'Guyana' },
  { code: 'HKD', name: 'dólar hongkonés', symbol: '$', digits: 2, region: 'Hong Kong' },
  { code: 'HNL', name: 'lempira hondureño', symbol: 'L', digits: 2, region: 'Honduras' },
  { code: 'HRK', name: 'kuna croata', symbol: 'kn', digits: 2, region: 'Croacia' },
  { code: 'HTG', name: 'gurde haitiano', symbol: 'HTG', digits: 2, region: 'Haití' },
  { code: 'HUF', name: 'forinto húngaro', symbol: 'Ft', digits: 0, region: 'Hungría' },
  { code: 'IDR', name: 'rupia indonesia', symbol: 'Rp', digits: 0, region: 'Indonesia' },
  { code: 'ILS', name: 'nuevo séquel israelí', symbol: '₪', digits: 2, region: 'Israel' },
  { code: 'INR', name: 'rupia india', symbol: '₹', digits: 2, region: 'India' },
  { code: 'IQD', name: 'dinar iraquí', symbol: 'IQD', digits: 0, region: 'Irak' },
  { code: 'IRR', name: 'rial iraní', symbol: 'IRR', digits: 0, region: 'Irán' },
  { code: 'ISK', name: 'corona islandesa', symbol: 'kr', digits: 0, region: 'Islandia' },
  { code: 'JMD', name: 'dólar jamaicano', symbol: '$', digits: 2, region: 'Jamaica' },
  { code: 'JOD', name: 'dinar jordano', symbol: 'JOD', digits: 3, region: 'Jordania' },
  { code: 'JPY', name: 'yen japonés', symbol: '¥', digits: 0, region: 'Japón' },
  { code: 'KES', name: 'chelín keniano', symbol: 'KES', digits: 2, region: 'Kenia' },
  { code: 'KGS', name: 'som kirguís', symbol: '⃀', digits: 2, region: 'Kirguistán' },
  { code: 'KHR', name: 'riel camboyano', symbol: '៛', digits: 2, region: 'Camboya' },
  { code: 'KMF', name: 'franco comorense', symbol: 'CF', digits: 0, region: 'Comoras' },
  { code: 'KPW', name: 'won norcoreano', symbol: '₩', digits: 0, region: 'Corea del Norte' },
  { code: 'KRW', name: 'won surcoreano', symbol: '₩', digits: 0, region: 'Corea del Sur' },
  { code: 'KWD', name: 'dinar kuwaití', symbol: 'KWD', digits: 3, region: 'Kuwait' },
  {
    code: 'KYD',
    name: 'dólar de las Islas Caimán',
    symbol: '$',
    digits: 2,
    region: 'Islas Caimán',
  },
  { code: 'KZT', name: 'tengue kazajo', symbol: '₸', digits: 2, region: 'Kazajistán' },
  { code: 'LAK', name: 'kip laosiano', symbol: '₭', digits: 0, region: 'Laos' },
  { code: 'LBP', name: 'libra libanesa', symbol: 'L£', digits: 0, region: 'Líbano' },
  { code: 'LKR', name: 'rupia esrilanquesa', symbol: 'Rs', digits: 2, region: 'Sri Lanka' },
  { code: 'LRD', name: 'dólar liberiano', symbol: '$', digits: 2, region: 'Liberia' },
  { code: 'LSL', name: 'loti lesotense', symbol: 'LSL', digits: 2, region: 'Lesoto' },
  { code: 'LYD', name: 'dinar libio', symbol: 'LYD', digits: 3, region: 'Libia' },
  { code: 'MAD', name: 'dírham marroquí', symbol: 'MAD', digits: 2, region: 'Marruecos' },
  { code: 'MDL', name: 'leu moldavo', symbol: 'MDL', digits: 2, region: 'Moldavia' },
  { code: 'MGA', name: 'ariari malgache', symbol: 'Ar', digits: 0, region: 'Madagascar' },
  { code: 'MKD', name: 'dinar macedonio', symbol: 'MKD', digits: 2, region: 'Macedonia del Norte' },
  { code: 'MMK', name: 'kiat de Myanmar', symbol: 'K', digits: 0, region: 'Birmania' },
  { code: 'MNT', name: 'tugrik mongol', symbol: '₮', digits: 2, region: 'Mongolia' },
  { code: 'MOP', name: 'pataca macaense', symbol: 'MOP', digits: 2, region: 'Macao' },
  { code: 'MRU', name: 'uguiya mauritano', symbol: 'MRU', digits: 2, region: 'Mauritania' },
  { code: 'MUR', name: 'rupia mauriciana', symbol: 'Rs', digits: 2, region: 'Mauricio' },
  { code: 'MVR', name: 'rufiya maldiva', symbol: 'MVR', digits: 2, region: 'Maldivas' },
  { code: 'MWK', name: 'kuacha malauí', symbol: 'MWK', digits: 2, region: 'Malaui' },
  { code: 'MXN', name: 'peso mexicano', symbol: '$', digits: 2, region: 'México' },
  { code: 'MYR', name: 'ringit malasio', symbol: 'RM', digits: 2, region: 'Malasia' },
  { code: 'MZN', name: 'metical mozambiqueño', symbol: 'MZN', digits: 2, region: 'Mozambique' },
  { code: 'NAD', name: 'dólar namibio', symbol: '$', digits: 2, region: 'Namibia' },
  { code: 'NGN', name: 'naira nigeriano', symbol: '₦', digits: 2, region: 'Nigeria' },
  { code: 'NIO', name: 'córdoba oro', symbol: 'C$', digits: 2, region: 'Nicaragua' },
  { code: 'NOK', name: 'corona noruega', symbol: 'kr', digits: 2, region: 'Noruega' },
  { code: 'NPR', name: 'rupia nepalí', symbol: 'Rs', digits: 2, region: 'Nepal' },
  { code: 'NZD', name: 'dólar neozelandés', symbol: '$', digits: 2, region: 'Nueva Zelanda' },
  { code: 'OMR', name: 'rial omaní', symbol: 'OMR', digits: 3, region: 'Omán' },
  { code: 'PAB', name: 'balboa panameño', symbol: 'PAB', digits: 2, region: 'Panamá' },
  { code: 'PEN', name: 'sol peruano', symbol: 'PEN', digits: 2, region: 'Perú' },
  { code: 'PGK', name: 'kina papú', symbol: 'PGK', digits: 2, region: 'Papúa Nueva Guinea' },
  { code: 'PHP', name: 'peso filipino', symbol: '₱', digits: 2, region: 'Filipinas' },
  { code: 'PKR', name: 'rupia pakistaní', symbol: 'Rs', digits: 0, region: 'Pakistán' },
  { code: 'PLN', name: 'esloti polaco', symbol: 'zł', digits: 2, region: 'Polonia' },
  { code: 'PYG', name: 'guaraní paraguayo', symbol: '₲', digits: 0, region: 'Paraguay' },
  { code: 'QAR', name: 'rial catarí', symbol: 'QAR', digits: 2, region: 'Catar' },
  { code: 'RON', name: 'leu rumano', symbol: 'L', digits: 2, region: 'Rumanía' },
  { code: 'RSD', name: 'dinar serbio', symbol: 'RSD', digits: 2, region: 'Serbia' },
  { code: 'RUB', name: 'rublo ruso', symbol: '₽', digits: 2, region: 'Rusia' },
  { code: 'RWF', name: 'franco ruandés', symbol: 'RF', digits: 0, region: 'Ruanda' },
  { code: 'SAR', name: 'rial saudí', symbol: 'SAR', digits: 2, region: 'Arabia Saudí' },
  { code: 'SBD', name: 'dólar salomonense', symbol: '$', digits: 2, region: 'Islas Salomón' },
  { code: 'SCR', name: 'rupia seychellense', symbol: 'SCR', digits: 2, region: 'Seychelles' },
  { code: 'SDG', name: 'libra sudanesa', symbol: 'SDG', digits: 2, region: 'Sudán' },
  { code: 'SEK', name: 'corona sueca', symbol: 'kr', digits: 2, region: 'Suecia' },
  { code: 'SGD', name: 'dólar singapurense', symbol: '$', digits: 2, region: 'Singapur' },
  { code: 'SHP', name: 'libra de Santa Elena', symbol: '£', digits: 2, region: 'Santa Elena' },
  { code: 'SLE', name: 'leona sierraleonesa', symbol: 'SLE', digits: 2, region: 'Sierra Leona' },
  { code: 'SOS', name: 'chelín somalí', symbol: 'SOS', digits: 0, region: 'Somalia' },
  { code: 'SRD', name: 'dólar surinamés', symbol: '$', digits: 2, region: 'Surinam' },
  { code: 'SSP', name: 'libra sursudanesa', symbol: '£', digits: 2, region: 'Sudán del Sur' },
  {
    code: 'STN',
    name: 'dobra santotomense',
    symbol: 'Db',
    digits: 2,
    region: 'Santo Tomé y Príncipe',
  },
  { code: 'SVC', name: 'colón salvadoreño', symbol: 'SVC', digits: 2, region: 'El Salvador' },
  { code: 'SYP', name: 'libra siria', symbol: '£', digits: 0, region: 'Siria' },
  { code: 'SZL', name: 'lilangeni esuatiní', symbol: 'SZL', digits: 2, region: 'Esuatini' },
  { code: 'THB', name: 'bat tailandés', symbol: '฿', digits: 2, region: 'Tailandia' },
  { code: 'TJS', name: 'somoni tayiko', symbol: 'TJS', digits: 2, region: 'Tayikistán' },
  { code: 'TMT', name: 'manat turcomano', symbol: 'TMT', digits: 2, region: 'Turkmenistán' },
  { code: 'TND', name: 'dinar tunecino', symbol: 'TND', digits: 3, region: 'Túnez' },
  { code: 'TOP', name: 'paanga tongano', symbol: 'T$', digits: 2, region: 'Tonga' },
  { code: 'TRY', name: 'lira turca', symbol: '₺', digits: 2, region: 'Turquía' },
  {
    code: 'TTD',
    name: 'dólar de Trinidad y Tobago',
    symbol: '$',
    digits: 2,
    region: 'Trinidad y Tobago',
  },
  { code: 'TWD', name: 'nuevo dólar taiwanés', symbol: 'NT$', digits: 2, region: 'Taiwán' },
  { code: 'TZS', name: 'chelín tanzano', symbol: 'TZS', digits: 2, region: 'Tanzania' },
  { code: 'UAH', name: 'grivna ucraniana', symbol: '₴', digits: 2, region: 'Ucrania' },
  { code: 'UGX', name: 'chelín ugandés', symbol: 'UGX', digits: 0, region: 'Uganda' },
  { code: 'USD', name: 'dólar estadounidense', symbol: '$', digits: 2, region: 'Estados Unidos' },
  { code: 'UYU', name: 'peso uruguayo', symbol: '$', digits: 2, region: 'Uruguay' },
  { code: 'UZS', name: 'sum uzbeko', symbol: 'UZS', digits: 2, region: 'Uzbekistán' },
  { code: 'VES', name: 'bolívar venezolano', symbol: 'VES', digits: 2, region: 'Venezuela' },
  { code: 'VND', name: 'dong vietnamita', symbol: '₫', digits: 0, region: 'Vietnam' },
  { code: 'VUV', name: 'vatu vanuatense', symbol: 'VUV', digits: 0, region: 'Vanuatu' },
  { code: 'WST', name: 'tala samoano', symbol: 'WST', digits: 2, region: 'Samoa' },
  {
    code: 'XAF',
    name: 'franco CFA de África Central',
    symbol: 'XAF',
    digits: 0,
    region: 'África Central',
  },
  {
    code: 'XCD',
    name: 'dólar del Caribe Oriental',
    symbol: '$',
    digits: 2,
    region: 'Caribe Oriental',
  },
  {
    code: 'XOF',
    name: 'franco CFA de África Occidental',
    symbol: 'XOF',
    digits: 0,
    region: 'África Occidental',
  },
  { code: 'XPF', name: 'franco CFP', symbol: 'CFPF', digits: 0, region: 'Polinesia Francesa' },
  { code: 'YER', name: 'rial yemení', symbol: 'YER', digits: 0, region: 'Yemen' },
  { code: 'ZAR', name: 'rand sudafricano', symbol: 'R', digits: 2, region: 'Sudáfrica' },
  { code: 'ZMW', name: 'kuacha zambiano', symbol: 'ZK', digits: 2, region: 'Zambia' },
  { code: 'ZWG', name: 'oro zimbabuense', symbol: 'ZWG', digits: 2, region: 'Zimbabue' },
] as const satisfies readonly CurrencyMeta[];

/** Union of every supported code — gives compile-time checking at call sites. */
export type CurrencyCode = (typeof CURRENCIES)[number]['code'];

const BY_CODE: ReadonlyMap<string, CurrencyMeta> = new Map(
  CURRENCIES.map((currency) => [currency.code, currency]),
);

export function isCurrencyCode(value: unknown): value is CurrencyCode {
  return typeof value === 'string' && BY_CODE.has(value);
}

/**
 * Look up a currency. Throws on an unknown code: a missing currency is a
 * programming error, and silently returning a default would produce a wrong
 * price — the one failure mode this product cannot have.
 */
export function getCurrency(code: CurrencyCode): CurrencyMeta {
  const currency = BY_CODE.get(code);
  if (!currency) {
    throw new Error(`Unknown currency code: ${code}`);
  }
  return currency;
}

/** Symbols worn by more than one currency, so they cannot identify one. */
const AMBIGUOUS_SYMBOLS: ReadonlySet<string> = new Set(
  CURRENCIES.map((currency) => currency.symbol).filter(
    (symbol, index, all) => all.indexOf(symbol) !== index,
  ),
);

/**
 * What leads the amount field, so the traveler knows what they are typing.
 *
 * The symbol, unless the symbol identifies nothing: 48 of these currencies
 * share one with another and 28 of them use `$`. A field reading `$ 25.000`
 * in Argentina says "dollars" to almost everyone, and the mistake runs in the
 * dangerous direction — believing you are entering dollars while entering
 * pesos.
 *
 * Derived from the table rather than from a hand-kept list of offenders, so a
 * collision introduced by a future regeneration is covered the day it appears.
 * It is also the call CLDR already makes for the formatted result, where es-ES
 * renders ARS as `25.000,00 ARS` and never as `$`.
 */
export function currencyMarker(code: CurrencyCode): string {
  const { symbol } = getCurrency(code);
  return AMBIGUOUS_SYMBOLS.has(symbol) ? code : symbol;
}
